version: '3'
services:
  mongodb:
    image: mongo:5.0
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=n1rvanA!
  topology:
    image: registry.gitlab.com/cavepot/tectonic/prod:latest
    #env_file:
    #  - gitlab.env
    ports:
      - 80:80
      - 27017:27017
    entrypoint: ["npm", "run", "serve_prod"]
    depends_on:
      - mongodb
  migrations:
    image: registry.gitlab.com/cavepot/tectonic/prod:latest
    #env_file:
    #  - gitlab.env
    ports:
      - 80:80
      - 27017:27017
    entrypoint: ["npm", "run", "migrate_run_prod"]
    depends_on:
      - mongodb